name: test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run one script
        run: echo "one script"
      - name: Run two script
        run: echo "two script"