name: upper-build 测试
on:
  push:
    branches:
      - main
    paths:
      - "./github/workflows/upper-build.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: zhangchen1

        run: go version

